[pyprland]
plugins = ["scratchpads"]

[scratchpads.telegram]
animation = "fromRight"        # Выезжает справа
command = "/home/nezerkill/Загрузки/tsetup.6.5.1/Telegram/Telegram"   # Команда запуска
class = "org.telegram.desktop._6c69cf97339e7074281db0f79e937723" # Класс окна
size = "45% 95%"               # Ширина 45%, высота 95%
max_size = "1920px 100%"
unfocus = "hide"               # Скрывать, если кликнули на другое окно
lazy = true                    # Запускать только при первом вызове
margin = 20
